### ISSUE TITLE
Its this possible?

### ISSUE THREAD

**Issue by mindiw01** [distritic/mdt#10]
My server is not using the table characters, we have all data from players on table users, like firstname/lastname/dob & sex.
Its any method to make this tablet work without table characters?

**Comment by distritic** [comment]
![image](https://user-images.githubusercontent.com/46497806/99601997-81213f00-29f8-11eb-8868-243d8472dac8.png)

Please actually read the **full** installation instructions.
https://forum.cfx.re/t/esx-mobile-data-terminal-reports-warrants-calls-searches-more/1701472/77
