### ISSUE TITLE
Calls

### ISSUE THREAD

**Issue by tom-acco** [distritic/mdt#11]
I understand you're not further developing this, but did you ever finish implementing the calls feature? I can see there is a bunch of client code to handle the functionality, but the server events and SQL table seems to be missing.

**Comment by distritic** [comment]
1. Calls are stored in memory and don't use an SQL table, that would be very resource intensive and completely unnecessary.
2. There are server events for handling them, I don't understand how you didn't notice that.
3. The original post has very clear documentation. Please read it before opening an issue.

![image](https://user-images.githubusercontent.com/46497806/103958953-51fc9380-5146-11eb-9fae-4ee0c8362e64.png)
