### ISSUE TITLE
how to do Calls work?

### ISSUE THREAD

**Issue by fucekar** [distritic/mdt#4]

**Comment by distritic** [comment]
This is clearly mentioned on the original topic (FiveM):

There’s a server-side event you might want to know about so that you can trigger this when a call comes through and want it to show on the MDT. 

```lua
-- Create a new 911 call in the MDT under the 'Calls' tab.
TriggerEvent("mdt:newCall", details --[[string]], caller --[[int]], coords --[[vector3]])
```
