### ISSUE TITLE
fine_types wont show up on relog

### ISSUE THREAD

**Issue by Nikwitz** [distritic/mdt#8]
Hi there.

Many people have the issue about the fine_types is not showing up when thet reconnect to the server. It's like the fine_types only gets deployed once on restart and not when peoples character is loading. 

Can you help?

Best Regards,
Nikwitz.

**Comment by distritic** [comment]
https://github.com/distritic/mdt/blob/c1e14e0ac3fd1ca08ce918f9ab68971fe09cb817/cl_mdt.lua#L26
The event to fetch data from the `fine_types` table is called when you join. Not entirely sure why the result wouldn't be returned to the client?

If you find a solution feel free to make a pull request, but I won't be updating this anymore.
